// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBINvtkxErbWz7XhX6I47KgsyP4EBplkwQ',
    appId: '1:578161971720:web:39c9aa5ae748f2dd86f7bd',
    messagingSenderId: '578161971720',
    projectId: 'traveller-bfedd',
    authDomain: 'traveller-bfedd.firebaseapp.com',
    storageBucket: 'traveller-bfedd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ0XTZhZhdQ_pk8Ecagb7zWjUCjDnweCw',
    appId: '1:578161971720:android:8d1640e7e06e1e6086f7bd',
    messagingSenderId: '578161971720',
    projectId: 'traveller-bfedd',
    storageBucket: 'traveller-bfedd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsex6ktojrh7hsY2CXC-W6ny9U4sbkTCM',
    appId: '1:578161971720:ios:c3db11c002eb8c3486f7bd',
    messagingSenderId: '578161971720',
    projectId: 'traveller-bfedd',
    storageBucket: 'traveller-bfedd.firebasestorage.app',
    iosBundleId: 'com.example.traveller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsex6ktojrh7hsY2CXC-W6ny9U4sbkTCM',
    appId: '1:578161971720:ios:c3db11c002eb8c3486f7bd',
    messagingSenderId: '578161971720',
    projectId: 'traveller-bfedd',
    storageBucket: 'traveller-bfedd.firebasestorage.app',
    iosBundleId: 'com.example.traveller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBINvtkxErbWz7XhX6I47KgsyP4EBplkwQ',
    appId: '1:578161971720:web:9cf5f1a3e28f86d186f7bd',
    messagingSenderId: '578161971720',
    projectId: 'traveller-bfedd',
    authDomain: 'traveller-bfedd.firebaseapp.com',
    storageBucket: 'traveller-bfedd.firebasestorage.app',
  );
}
